In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Data/sales_data.csv")

In [3]:
df.head()

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51

In [4]:
df = df.drop_duplicates()

In [5]:
df = df.dropna()

In [6]:
df['date'] = pd.to_datetime(df['date'])

KeyError: 'date'

In [7]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

ValueError: time data "Jan 5 2023" doesn't match format "%Y-%m-%d", at position 11. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [8]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [9]:
df['Order_Date'].isnull().sum()

np.int64(2)

In [10]:
df.to_csv("cleaned_sales.csv", index=False)

In [11]:
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
...,...,...,...,...,...,...,...,...,...,...,...
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1,160.16,PayPal,Cancelled,160.160
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300

In [12]:
df.isnull().sum()

ID                0
 Customer_Name    0
Order_ID          0
Order_Date        2
 Product          0
Category          0
Quantity          0
Price             0
Payment_Method    0
Status            0
Total             0
dtype: int64

In [13]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df = df.dropna()

In [14]:
df.isnull().sum()

ID                0
 Customer_Name    0
Order_ID          0
Order_Date        0
 Product          0
Category          0
Quantity          0
Price             0
Payment_Method    0
Status            0
Total             0
dtype: int64